//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsProjectAdvanced.Input {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginCredentials {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginCredentials() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarsProjectAdvanced.Input.LoginCredentials", typeof(LoginCredentials).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonono.
        /// </summary>
        internal static string confirmpwd {
            get {
                return ResourceManager.GetString("confirmpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okokok.
        /// </summary>
        internal static string currentpwd {
            get {
                return ResourceManager.GetString("currentpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonono.
        /// </summary>
        internal static string newpwd {
            get {
                return ResourceManager.GetString("newpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okokok.
        /// </summary>
        internal static string passWord {
            get {
                return ResourceManager.GetString("passWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonono.
        /// </summary>
        internal static string passWord2 {
            get {
                return ResourceManager.GetString("passWord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5000/.
        /// </summary>
        internal static string urlLink {
            get {
                return ResourceManager.GetString("urlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testingroro5@gmail.com.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
    }
}
